#!/usr/bin/env python
# -*- coding: utf-8 -*-
# This file is automatically generated

__version_info__: tuple[int, int, int] = (2, 1, 0)
__version__ = ".".join(map(str, __version_info__))
__release_date__ = "2026-09-27"
