#!/usr/bin/env python
# -*- coding: utf-8 -*-
# =============================================================================
#                    Author: Florent TOURNOIS | License: MIT                   
# =============================================================================

# This file is automatically generated

__version_info__ = (1, 0, 41)
__version__ = ".".join(map(str, __version_info__))
__release_date__ = '2026-01-19'
