@ECHO OFF
REM ===========================================================================
REM                   Author: Florent TOURNOIS | License: MIT                  
REM ===========================================================================

REM This file is automatically generated
SET VERSION=1.0.41
