#!/usr/bin/env python
# -*- coding: utf-8 -*-
# ===============================================================================
#                 Author: Florent TOURNOIS | License: MIT
# ===============================================================================
"""Safe local helpers for versioning and release validation.

This script never pushes a tag and never uploads a distribution. Publishing is
performed by the trusted GitHub Actions workflow after a GitHub release is
created from a verified tag.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from datetime import date
from pathlib import Path
from typing import Final, Sequence


ROOT: Final = Path(__file__).resolve().parents[1]
VERSION_PY: Final = ROOT / "pymdtools" / "version.py"
VERSION_BAT: Final = ROOT / "pymdtools" / "version.bat"
DIST_DIR: Final = ROOT / "dist"
DISTRIBUTION_NAME: Final = "pymdtools"
VERSION_RE: Final = re.compile(
    r"^__version_info__\s*=\s*\((\d+),\s*(\d+),\s*(\d+)\)\s*$",
    re.MULTILINE,
)
BAT_VERSION_RE: Final = re.compile(r"^SET VERSION=(\d+)\.(\d+)\.(\d+)\s*$", re.MULTILINE)


class ReleaseError(RuntimeError):
    """Raised when a release invariant is not satisfied."""


def run_git(*args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
    """Run Git without invoking a shell."""
    return subprocess.run(
        ["git", *args],
        cwd=ROOT,
        check=check,
        text=True,
        capture_output=True,
    )


def parse_python_version(text: str) -> tuple[int, int, int]:
    """Extract ``__version_info__`` from ``version.py`` text."""
    match = VERSION_RE.search(text)
    if match is None:
        raise ReleaseError("cannot parse pymdtools/version.py")
    major, minor, patch = match.groups()
    return int(major), int(minor), int(patch)


def parse_batch_version(text: str) -> tuple[int, int, int]:
    """Extract ``SET VERSION`` from ``version.bat`` text."""
    match = BAT_VERSION_RE.search(text)
    if match is None:
        raise ReleaseError("cannot parse pymdtools/version.bat")
    major, minor, patch = match.groups()
    return int(major), int(minor), int(patch)


def current_version() -> tuple[int, int, int]:
    """Return the working-tree package version."""
    return parse_python_version(VERSION_PY.read_text(encoding="utf-8"))


def version_string(version: tuple[int, int, int] | None = None) -> str:
    """Return a dotted version string."""
    selected = current_version() if version is None else version
    return ".".join(map(str, selected))


def require_clean_worktree() -> None:
    """Refuse release mutations from a dirty or untracked worktree."""
    status = run_git("status", "--porcelain", "--untracked-files=normal").stdout.strip()
    if status:
        raise ReleaseError(
            "working tree is not clean; commit or stash every change before continuing"
        )


def verify_version_files() -> str:
    """Ensure Python and batch version files contain the same version."""
    version = current_version()
    batch_version = parse_batch_version(VERSION_BAT.read_text(encoding="utf-8"))
    if batch_version != version:
        raise ReleaseError(
            f"version mismatch: version.py={version_string(version)} "
            f"version.bat={version_string(batch_version)}"
        )
    return version_string(version)


def write_version(version: tuple[int, int, int]) -> None:
    """Replace the Python and batch version files from prepared temp files."""
    dotted = version_string(version)
    python_text = (
        "#!/usr/bin/env python\n"
        "# -*- coding: utf-8 -*-\n"
        "# This file is automatically generated\n\n"
        f"__version_info__ = {version!r}\n"
        '__version__ = ".".join(map(str, __version_info__))\n'
        f"__release_date__ = {date.today().isoformat()!r}\n"
    )
    batch_text = (
        "@ECHO OFF\r\n"
        "REM This file is automatically generated\r\n"
        f"SET VERSION={dotted}\r\n"
    )

    python_tmp = VERSION_PY.with_suffix(".py.tmp")
    batch_tmp = VERSION_BAT.with_suffix(".bat.tmp")
    try:
        python_tmp.write_text(python_text, encoding="utf-8", newline="\n")
        batch_tmp.write_text(batch_text, encoding="utf-8", newline="")
        python_tmp.replace(VERSION_PY)
        batch_tmp.replace(VERSION_BAT)
    finally:
        python_tmp.unlink(missing_ok=True)
        batch_tmp.unlink(missing_ok=True)


def bump_version(part: str) -> str:
    """Bump one semantic version component from a clean tree."""
    if part not in {"major", "minor", "patch"}:
        raise ReleaseError(f"unknown version component: {part}")
    require_clean_worktree()
    major, minor, patch = current_version()
    if part == "major":
        next_version = (major + 1, 0, 0)
    elif part == "minor":
        next_version = (major, minor + 1, 0)
    else:
        next_version = (major, minor, patch + 1)
    write_version(next_version)
    return version_string(next_version)


def create_tag() -> str:
    """Create one annotated local tag after validating release invariants."""
    require_clean_worktree()
    version = verify_version_files()
    tag = f"v{version}"
    exists = run_git("rev-parse", "--quiet", "--verify", f"refs/tags/{tag}", check=False)
    if exists.returncode == 0:
        raise ReleaseError(f"tag already exists: {tag}")
    run_git("tag", "--annotate", tag, "--message", f"Release {version}")
    return tag


def verify_tag(tag: str | None = None) -> str:
    """Verify that the selected tag points at HEAD and matches version files."""
    require_clean_worktree()
    version = verify_version_files()
    expected = f"v{version}"
    selected = expected if tag is None else tag
    if selected != expected:
        raise ReleaseError(f"tag/version mismatch: tag={selected} package={version}")
    tag_object = run_git("cat-file", "-t", f"refs/tags/{selected}", check=False)
    if tag_object.returncode != 0:
        raise ReleaseError(f"tag does not exist: {selected}")
    if tag_object.stdout.strip() != "tag":
        raise ReleaseError(f"release tag must be annotated: {selected}")
    tags_at_head = set(run_git("tag", "--points-at", "HEAD").stdout.splitlines())
    if selected not in tags_at_head:
        raise ReleaseError(f"{selected} does not point at HEAD")
    return selected


def _reset_dist_dir() -> None:
    """Remove only the repository's real ``dist`` directory."""
    root = ROOT.resolve()
    resolved_dist = DIST_DIR.resolve()
    if resolved_dist.parent != root or DIST_DIR.is_symlink():
        raise ReleaseError(f"refusing to remove unsafe distribution path: {DIST_DIR}")
    if DIST_DIR.exists():
        if not DIST_DIR.is_dir():
            raise ReleaseError(f"distribution path is not a directory: {DIST_DIR}")
        shutil.rmtree(DIST_DIR)


def _validated_artifacts() -> list[Path]:
    """Return exactly one wheel and one gzip source distribution."""
    if not DIST_DIR.is_dir():
        raise ReleaseError("build produced no distribution directory")
    entries = sorted(DIST_DIR.iterdir())
    artifacts = [path for path in entries if path.is_file()]
    wheels = [path for path in artifacts if path.suffix == ".whl"]
    sdists = [path for path in artifacts if path.name.endswith(".tar.gz")]
    unexpected = [path for path in entries if path not in wheels and path not in sdists]
    if len(wheels) != 1 or len(sdists) != 1 or unexpected:
        names = ", ".join(path.name for path in artifacts) or "none"
        raise ReleaseError(
            "build must produce exactly one wheel and one .tar.gz source distribution; "
            f"found: {names}"
        )
    version = version_string()
    if not wheels[0].name.startswith(f"{DISTRIBUTION_NAME}-{version}-"):
        raise ReleaseError(f"wheel filename does not match version {version}: {wheels[0].name}")
    expected_sdist = f"{DISTRIBUTION_NAME}-{version}.tar.gz"
    if sdists[0].name != expected_sdist:
        raise ReleaseError(
            f"source distribution filename does not match version {version}: {sdists[0].name}"
        )
    return artifacts


def _utf8_subprocess_env() -> dict[str, str]:
    """Use deterministic UTF-8 output for nested Python build tools."""
    env = os.environ.copy()
    env["PYTHONUTF8"] = "1"
    env["PYTHONIOENCODING"] = "utf-8"
    return env


def build_distributions(*, allow_dirty: bool = False) -> list[Path]:
    """Build wheel/sdist and validate both with Twine."""
    if not allow_dirty:
        require_clean_worktree()
    _reset_dist_dir()
    env = _utf8_subprocess_env()
    subprocess.run([sys.executable, "-m", "build"], cwd=ROOT, check=True, env=env)
    artifacts = _validated_artifacts()
    subprocess.run(
        [sys.executable, "-m", "twine", "check", "--strict", *map(str, artifacts)],
        cwd=ROOT,
        check=True,
        env=env,
    )
    return artifacts


def audit_tags() -> list[str]:
    """Return historical version tags whose committed version does not match."""
    mismatches: list[str] = []
    tags = run_git("tag", "--list", "v[0-9]*", "--sort=version:refname").stdout.splitlines()
    for tag in tags:
        shown = run_git("show", f"{tag}:pymdtools/version.py", check=False)
        if shown.returncode != 0:
            mismatches.append(f"{tag}: version.py missing")
            continue
        try:
            committed = version_string(parse_python_version(shown.stdout))
        except ReleaseError as exc:
            mismatches.append(f"{tag}: {exc}")
            continue
        if tag != f"v{committed}":
            mismatches.append(f"{tag}: contains version {committed}")
    return mismatches


def build_parser() -> argparse.ArgumentParser:
    """Create the command-line parser."""
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    bump = subparsers.add_parser("bump", help="bump version files from a clean tree")
    bump.add_argument("part", choices=("major", "minor", "patch"), nargs="?", default="patch")

    subparsers.add_parser("tag", help="create a verified annotated local tag")
    verify = subparsers.add_parser("verify-tag", help="verify tag, HEAD and package version")
    verify.add_argument("tag", nargs="?")

    build = subparsers.add_parser("build", help="build and run strict Twine checks")
    build.add_argument("--allow-dirty", action="store_true")
    subparsers.add_parser("audit-tags", help="report historical tag/version mismatches")
    subparsers.add_parser("check", help="validate matching version files")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Run the selected release command."""
    args = build_parser().parse_args(argv)
    try:
        if args.command == "bump":
            print(f"Version updated to {bump_version(args.part)}; review and commit both files.")
        elif args.command == "tag":
            print(f"Created local tag {create_tag()}; inspect it before pushing that tag only.")
        elif args.command == "verify-tag":
            print(f"Verified {verify_tag(args.tag)}")
        elif args.command == "build":
            for artifact in build_distributions(allow_dirty=args.allow_dirty):
                print(artifact.relative_to(ROOT))
        elif args.command == "audit-tags":
            mismatches = audit_tags()
            if mismatches:
                print("Historical tag mismatches:", file=sys.stderr)
                for mismatch in mismatches:
                    print(f"- {mismatch}", file=sys.stderr)
                return 1
            print("All version tags match their committed package version.")
        else:
            print(f"Version files agree on {verify_version_files()}")
    except (OSError, ReleaseError, subprocess.CalledProcessError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
